### ISSUE TITLE
LessKeepRelativeDirectory and linked files

### ISSUE THREAD

**Issue by maxtoroq** [Jehran/LessMsbuildTasks#12]
Would it be possible to make `LessKeepRelativeDirectory = true` work with linked files (_Add as Link_)?

**Comment by maxtoroq** [comment]
There's a workaround, instead of adding a linked file, create a file with the same name and `@import` the original file.

**Comment by Jehran** [comment]
This is outside of my control as node.js (which is running the actual less compilation) has no knowledge of the project structure inside Visual Studio. This workaround might be the only supported way to handle this.
