### ISSUE TITLE
Move content\LessMsbuildTasks.txt to readme.txt

### ISSUE THREAD

**Issue by maxtoroq** [Jehran/LessMsbuildTasks#2]
If you include a readme.txt file at the root of your package NuGet will open it when you install it, no need to add the file to the project.

BTW, good job!

**Comment by Jehran** [comment]
Released in version 1.0.8

**Comment by maxtoroq** [comment]
There was a side effect to this change. Because the package now doesn't contain any libs or content, NuGet treats it as a *solution* package. A `.nuget` solution folder is added with a `packages.config` file, and the import is not automatically added to the target project, because as far as NuGet is concerned there's no target project.

See [Import MSBuild targets and props files into project](https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project), perhaps that would be a good way to do it?

**Comment by Jehran** [comment]
Thank you, this should be fixed on version 1.0.9 now up on NuGet.

**Comment by maxtoroq** [comment]
Not working. NuGet docs says file should be named `{packageid}.targets`. In this case `LessMsbuildTasks.targets`, not `LessCompiler.targets`.

**Comment by Jehran** [comment]
Thank you for testing this so quicky. I just pushed 1.0.9.1 to fix this naming issue.

**Comment by maxtoroq** [comment]
Working perfectly, thanks.
