### ISSUE TITLE
 The "NodelessCompile" task was not given a value for the required parameter "OutputFolder". 

### ISSUE THREAD

**Issue by cherchyk** [Jehran/LessMsbuildTasks#4]
c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild hcp.Web\hcp.Web.csproj /p:Configuration=%_configuration% /p:Platform="AnyCPU" /P:DeployOnBuild=true;DeployTarget=Package;_PackageTempDir=..\%_mainDeployDir%\%_configuration%

C:\dev\hcp\packages\LessMsbuildTasks.1.0.6\tools\LessCompiler.targets(40,5): error MSB4044: The "NodelessCompile" task was not given a value for the required parameter "OutputFolder". [C:\dev\hcp\hcp.Web\hcp.Web.csproj]

**Comment by PaulCoetser** [comment]
I Also struggle with the same problem for 2 days now.  I don't know which way anymore

**Comment by Jehran** [comment]
Released in version 1.0.8
