### ISSUE TITLE
LessDisableUrlRewriting option not implemented

### ISSUE THREAD

**Issue by Kimberly190** [Jehran/LessMsbuildTasks#5]
The ReadMe lists this as an advanced option, but it doesn't appear to be implemented  There's no conditional around the corresponding argument - it's always included:

    //Add this option to make urls relative.
    args.Add( "--relative-urls" );

We need the ability to disable this - can you add the option (or add it back)?  Thanks!

**Comment by philai** [comment]
Yes please. We are in need of this too!

Problem comes from using Web Essentials in debug mode, but then use this tool to compile the {less} files on the build server. Relative paths are calculated differently because I need to override the icon font path in Bootstrap.

**Comment by Jehran** [comment]
Released in version 1.0.8
