### ISSUE TITLE
Where do I specify the MSBuild Properties

### ISSUE THREAD

**Issue by agrigg** [Jehran/LessMsbuildTasks#7]
I want to set a custom output for my compiled CSS files using the LessOutputDirectory property. Where do I set that property? Is there a file I need to add to my project?

**Comment by Jehran** [comment]
You can add the properties to the top of your project under the first "PropertyGroup" tag. The format is standard Xml syntax <PropertyName>Value</PropertyName>

**Comment by agrigg** [comment]
Thanks, in case anyone is wondering how to do this, Here is the XML I added to my .csproj file above the first PropertyGroup

  <PropertyGroup>
    <LessOutputDirectory Condition="$(LessOutputDirectory) == '' And $(WebProjectOutputDir) !=''">$(WebProjectOutputDir)\Styles\compiled\</LessOutputDirectory>
    <LessOutputDirectory Condition="$(LessOutputDirectory) == '' And $(WebProjectOutputDir) ==''">$(MSBuildProjectDirectory)\Styles\compiled\</LessOutputDirectory>
    <LessKeepRelativeDirectory>false</LessKeepRelativeDirectory>
  </PropertyGroup>
